### PR TITLE
fix: make each flavor in line with each other

### PR DESCRIPTION
**Pull request by GenShibe**
this PR basically attempts to make each fiavor file have the same variables and fixes some of the colors not being ctp themed

### CODE REVIEW

**Comment by GenShibe** [comment]
it's a lot of commits because i was changing accent + trying to fix any unthemed elements that i found

**Comment by riivx** [comment]
hi!
first of all - thanks for this huge PR!
no issues except a single one: is it possible to do anything with this header color? should be white, but in case if it's used anywhere else, that should be okay
thing

**Comment by GenShibe** [comment]
> hi!
> 
> first of all - thanks for this huge PR!
> 
> no issues except a single one: is it possible to do anything with this header color? should be white, but in case if it's used anywhere else, that should be okay
> 
> thing
> 
> 

if i could figure out how it's being themed, sure

**Comment by riivx** [comment]
eh, it's not that big of a deal. i only see it being used in the "get nitro" thing, not that important imho. i guess i'll squash and merge then

**Pull request merged**
