### PR TITLE
font fixups for Bunny

### PR DESCRIPTION
**Pull request by anoraktrend**
fix the font files for bunny.

### CODE REVIEW

**Comment by anoraktrend** [comment]
Unfortunately, I have no idea as to WHY this happened, (I was using a similar font theme earlier), but there may be errors in the font selection that cause crashes. Once again, no clue as to what needs to be changed to fix it. But a temporary revert might be a good idea until I can fix the error.

**Comment by riivx** [comment]
hm, that's strange, let me test it once again

**Comment by riivx** [comment]
i haven't tested the fonts very deeply, but still, i don't encounter any crashes at all
if you have any, can you please send any screenshots or screen recordings of the issue?

**Comment by anoraktrend** [comment]
https://github.com/user-attachments/assets/08cb6ffe-ce28-4e52-8ba2-bf63fdff8c88

This occurs only when the fonts are installed, enabled, and 
[fonts.json](https://github.com/user-attachments/files/16507094/fonts.json) exists. Could be an issue in my version of bunny.

**Comment by riivx** [comment]
i tested on android, no crashes. might be ios-specific issue, but i'm not sure

**Pull request merged**
